# Default values for etcd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: quay.io/coreos/etcd
  tag: v3.2.4
  pullPolicy: IfNotPresent
storage:
  size: 1Gi
  accessModes: ReadWriteOnce
  class: fast
resources:
  limits:
    memory: 1Gi
  requests:
    memory: 500Mi
