kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etcd-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "{{ .Values.storage.class }}"
    "helm.sh/hook": "pre-install"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
