apiVersion: v1
kind: Service
metadata:
  name: couchbase-master-service
  labels:
    app: couchbase-master-service
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # "helm.sh/hook": "pre-install"
spec:
  clusterIP: None
  ports:
  - port: 4369
    name: erlang
  - port: 8091
    name: managment
  - port: 8092
    name: mapreduce
  - port: 8093
    name: query
  - port: 11210
    name: keyvalue
  selector:
    couchbase-worker: couchbase-worker
